---
title: "Dual Power Comparison"
output: html_document
params:
  fit: NA
  conf: NA
  maxes: NA
  dat: NA
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width=10,
  fig.height=4, 
  echo = FALSE, 
  include = TRUE)

library(dygraphs)
library(dplyr)
library(xts)
library(shiny)
library(dualR)

source("utils.R")
```

## Source Metadata Summary
```{r max, results='asis'}

cat(
  params$fit$f1$m 
)

get_devices_table(params$fit$f1$d)

cat("<br/><br/>")

if(!is.null(params$fit$f1_2$m)) {

cat(
  params$fit$f1_2$m
)

get_devices_table(params$fit$f1_2$d)

}

cat("<br/><br/>")

if(!is.null(params$fit$f2$m)) {

cat(
  params$fit$f2$m
)

get_devices_table(params$fit$f2$d)

}
```
## Critical Power Comparison
```{r max_table}
get_powercurve_table(params$maxes, params$conf)

```

```{r plot}
powercurve_plot(params$maxes, params$conf)
```

## Raw Data Plots

Double click for zoom full.
```{r plots, fig.width=10, fig.height=2.5}
dat <- params$dat

get_dygraph(dat$power)

get_dygraph(dat$heartrate)

get_dygraph(dat$elevation)

get_dygraph(dat$cadence)
```
