ui <- fluidPage(
  mainPanel(h1("Dual Power Comparison"),
            br(),
            p("This application accepts one or two (overlapping) fit files and creates a comparison report."),
            p("dualR is being provided as a service to the community. It is free and open source."),
            p(HTML('See <a href="https://github.com/dblodgett-cycling/dualR" target="_blank">the github repository</a> for more information or to ask questions.')),
            fixedRow(column(width = 6,
                            fileInput("f1", 
                                      label = p("Fit 1", bsButton("q1", label = "", 
                                                                  icon = icon("info"), 
                                                                  style = "info", 
                                                                  size = "extra-small")), 
                                      multiple = FALSE, 
                                      accept = c(".fit", ".zip")),
                            bsPopover(id = "q1", title = "Upload Help",
                                      content = "If upload fails, try zipping your fit file and upload again.",
                                      placement = "right", 
                                      trigger = "focus", 
                                      options = list(container = "body")),
                            textInput(inputId = "f1_label", label = "File 1 Label",
                                      width = "200px",
                                      placeholder = "e.g. Power Meter")),
                     column(width = 6,
                            fileInput("f2", "Fit 2", multiple = FALSE, accept = c(".fit", ".zip")),
                            textInput(inputId = "f2_label", label = "File 2 Label",
                                      width = "200px",
                                      placeholder = "e.g. Trainer"))),
            checkboxInput("trim", label = "Trim timeseries to overlapping parts.", value = FALSE),
            checkboxInput("offset", label = "Show timeseries offset controls."),
            checkboxInput("demo", "Demo: Check to use demo files."),
            actionButton(inputId = "generate", label = "Run Report", width = "200px"),
            conditionalPanel(condition = "input.offset && output.show",
                             dygraphOutput("summary_dygraph", height = "100px"),
              fixedRow(column(width = 6,
                              textInput("f1_offset", p("Fit 1 Offset", 
                                                       bsButton("q2", label = "", 
                                                                icon = icon("info"), 
                                                                style = "info", 
                                                                size = "extra-small")), 
                                        placeholder = "9999-99-99 99:99:99"),
                              bsPopover(id = "q2", title = "Offset Help",
                                        content = "Enter desired start time of this timeseries.",
                                        placement = "right", 
                                        trigger = "focus", 
                                        options = list(container = "body")
                              )),
                       column(width = 6,
                              textInput("f2_offset", "Fit 2 Offset", placeholder = "9999-99-99 99:99:99")))
            ),
            br(),
            conditionalPanel(condition = "output.show",
                             downloadButton("run_report", label = "Download Report"),
                             h3("Power Source Metadata"),
                             htmlOutput("f1_meta"),
                             h4("Connected Device Metadata"),
                             tableOutput("fit_1_devices"),
                             br(), br(),
                             htmlOutput("f2_meta"),
                             htmlOutput("fit_2_device_heading"),
                             tableOutput("fit_2_devices"),
                             br(),
                             h3("Critical Power Comparison"),
                             fixedRow(column(width = 3,
                                             br(),
                                             br(),
                                             tableOutput("powerCurve_table")),
                                      column(width = 9,
                                             plotOutput("powerCurve_plot"))),
                             p("NOTE: Critical powers are calculated on the overlapping portion of inputs only."),
                             br(),
                             p("Double click for zoom full."),
                             dygraphOutput("power_dygraph"),
                             dygraphOutput("hr_dygraph"),
                             dygraphOutput("ele_dygraph"),
                             dygraphOutput("cad_dygraph"))
  )
  
)
